# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 781, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newTaskButton = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.newTaskButton.setObjectName("newTaskButton")
        self.horizontalLayout_2.addWidget(self.newTaskButton)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.submitButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout_2.addWidget(self.submitButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox1.setObjectName("checkBox1")
        self.gridLayout_3.addWidget(self.checkBox1, 4, 0, 1, 1)
        self.task1Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.task1Label.setObjectName("task1Label")
        self.gridLayout_3.addWidget(self.task1Label, 4, 1, 1, 1)
        self.task2Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.task2Label.setObjectName("task2Label")
        self.gridLayout_3.addWidget(self.task2Label, 5, 1, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox3.setObjectName("checkBox3")
        self.gridLayout_3.addWidget(self.checkBox3, 6, 0, 1, 1)
        self.task3Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.task3Label.setObjectName("task3Label")
        self.gridLayout_3.addWidget(self.task3Label, 6, 1, 1, 1)
        self.task3TextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.task3TextBrowser.setObjectName("task3TextBrowser")
        self.gridLayout_3.addWidget(self.task3TextBrowser, 6, 2, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_3.addWidget(self.statusLabel, 2, 0, 1, 1)
        self.idLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.idLabel.setObjectName("idLabel")
        self.gridLayout_3.addWidget(self.idLabel, 2, 1, 1, 1)
        self.task2TextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.task2TextBrowser.setObjectName("task2TextBrowser")
        self.gridLayout_3.addWidget(self.task2TextBrowser, 5, 2, 1, 1)
        self.task1TextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.task1TextBrowser.setObjectName("task1TextBrowser")
        self.gridLayout_3.addWidget(self.task1TextBrowser, 4, 2, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox2.setObjectName("checkBox2")
        self.gridLayout_3.addWidget(self.checkBox2, 5, 0, 1, 1)
        self.descLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.descLabel.setObjectName("descLabel")
        self.gridLayout_3.addWidget(self.descLabel, 2, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TODO-GPT"))
        self.newTaskButton.setText(_translate("MainWindow", "New task"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.checkBox1.setText(_translate("MainWindow", "CheckBox"))
        self.task1Label.setText(_translate("MainWindow", "TextLabel"))
        self.task2Label.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox3.setText(_translate("MainWindow", "CheckBox"))
        self.task3Label.setText(_translate("MainWindow", "TextLabel"))
        self.statusLabel.setText(_translate("MainWindow", "Status"))
        self.idLabel.setText(_translate("MainWindow", "Id"))
        self.checkBox2.setText(_translate("MainWindow", "CheckBox"))
        self.descLabel.setText(_translate("MainWindow", "Description"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
